USE_CAMERA_STUB := true

# Platform
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := sc8830
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOOTLOADER_BOARD_NAME := SC7727S

# Assert
TARGET_OTA_ASSERT_DEVICE := j1pop3g,SM-J110H,J110H,SC7727S

# Kernel
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01000000 --tags_offset 0x00000100 
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_CONFIG := teamwin_j1pop3g_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/j1pop3g


TARGET_NO_BOOTLOADER				:= true
TARGET_NO_RADIOIMAGE				:= true

# PARTITION SIZE
BOARD_BOOTIMAGE_PARTITION_SIZE			:= 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE		:= 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE		:= 1158291200
BOARD_USERDATAIMAGE_PARTITION_SIZE		:= 209715200
BOARD_CACHEIMAGE_PARTITION_SIZE 		:= 69206016
BOARD_FLASH_BLOCK_SIZE					:= 131072
TARGET_USERIMAGES_USE_EXT4				:= true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE		:= ext4


# Resolution
TARGET_SCREEN_HEIGHT := 800
TARGET_SCREEN_WIDTH := 480

# Bootanimation
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR	:= device/samsung/j1pop3g/bluetooth
BOARD_HAVE_BLUETOOTH 						:= true
BOARD_BLUEDROID_VENDOR_CONF 				:= device/samsung/j1pop3g/bluetooth/libbt_vndcfg.txt
# Hardware rendering
USE_OPENGL_RENDERER 				:= true
BOARD_EGL_CFG 					:= device/samsung/j1pop3g/egl.cfg
BOARD_USE_MHEAP_SCREENSHOT                      := true
BOARD_EGL_WORKAROUND_BUG_10194508               := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK           := true
BOARD_EGL_NEEDS_FNW 				:= true
COMMON_GLOBAL_CFLAGS 				+= -DNEEDS_VECTORIMPL_SYMBOLS
COMMON_GLOBAL_CFLAGS                            += -DMR0_CAMERA_BLOB -DEGL_NEEDS_FNW -DMR0_AUDIO_BLOB -DSAMSUNG_BCM_AUDIO_BLOB -DSC8830_HWC
USE_OPENGL_RENDERER                             := true
USE_OVERLAY_COMPOSER_GPU                        := true
DEVICE_FORCE_VIDEO_GO_OVERLAYCOMPOSER           := true



# Charger
BOARD_CHARGER_ENABLE_SUSPEND := true
BOARD_CHARGING_MODE_BOOTING_LPM := /sys/class/power_supply/battery/batt_lp_charging

# Recovery
TARGET_RECOVERY_FSTAB := device/samsung/j1pop3g/recovery.fstab
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/class/android_usb/android0/f_mass_storage/lun%d/file"
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_HAS_NO_MISC_PARTITION := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_HAS_FLIPPED_SCREEN := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBA_8888
BOARD_USE_BGRA_8888 := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"

# don't take forever to wipe
BOARD_SUPPRESS_SECURE_ERASE := true
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD

